package net.brenig.pixelescape.game.worldgen

import net.brenig.pixelescape.game.World
import java.util.*

/**
 * TerrainGenerator used for generating terrain
 */
interface ITerrainGenerator {

    val weight: Int

    /**
     * generates terrain
     *
     * @param world                The World instance
     * @param lastPair             the previous TerrainPair
     * @param blocksToGenerate     the amount of blocks that are requested to get generated
     * @param generatedBlocksIndex index of the currently already generated blocks
     * @param random               random instance for world generation
     * @return amount of blocks generated
     */
    fun generate(world: World, lastPair: TerrainPair, blocksToGenerate: Int, generatedBlocksIndex: Int, random: Random): Int

    /**
     * Gets called to make sure the terrain generator can generate<br></br>
     * Does only get called once per generation cycle
     *
     * @param last the last currently generated TerrainPair
     * @return minimum amount of blocks that get generated by this ITerrainGenerator, return a value <= 0 if none
     */
    fun getMinGenerationLength(last: TerrainPair): Int
}
