package net.brenig.pixelescape.game.worldgen;

import net.brenig.pixelescape.game.World;

import java.util.Random;

/**
 * Created by Jonas Brenig on 15.08.2015.
 */
public interface ITerrainGenerator {

	/**
	 * generates terrain
	 *
	 * @param world The World instance
	 * @param lastPair the previous TerrainPair
	 * @param blocksToGenerate the amount of blocks that are requested to get generated
	 * @param generatedBlocksIndex index of the currently already generated blocks
	 * @param random random instance for world generation
	 * @return amount of blocks generated
	 */
	int generate(World world, TerrainPair lastPair, int blocksToGenerate, int generatedBlocksIndex, Random random);

	/**
	 * @return minimum amount of blocks that get generated by this ITerrainGenerator
	 */
	int getMinGenerationLength();
}
