package net.brenig.pixelescape.game.worldgen;

import net.brenig.pixelescape.game.World;

import java.util.Random;

/**
 * TerrainGenerator used for generating terrain
 */
public interface ITerrainGenerator {

	/**
	 * generates terrain
	 *
	 * @param world The World instance
	 * @param lastPair the previous TerrainPair
	 * @param blocksToGenerate the amount of blocks that are requested to get generated
	 * @param generatedBlocksIndex index of the currently already generated blocks
	 * @param random random instance for world generation
	 * @return amount of blocks generated
	 */
	int generate(World world, TerrainPair lastPair, int blocksToGenerate, int generatedBlocksIndex, Random random);

	/**
	 * Gets called to make sure the terrain generator can generate<br>
	 * Does only get called once per generation cycle
	 * @param last the last currently generated TerrainPair
	 * @return minimum amount of blocks that get generated by this ITerrainGenerator, return a value <= 0 if none
	 */
	int getMinGenerationLength(TerrainPair last);

	int getWeight();
}
